name: 'git-ftp-action'
author: 'Sebastian Popp <git-ftp-action@sebastianpopp.com> adatpted by Stefano Sanvito <stiwou@gmail.com>'
description: 'Uses git-ftp and GitHub actions to deploy a GitHub repository to a FTP/SFTP server.'
inputs:
  url:
    description: 'URL'
    required: true
  user:
    description: 'SFTP login name'
    required: true
  password:
    description: 'SFTP password'
    required: true
  syncroot:
    description: 'Specifies a local directory to sync from as if it were the git project root path.'
    required: false
    default: '.'
  options:
    description: 'Additional options'
    required: false
    default: '--auto-init'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'blue'
  icon: 'upload-cloud'
